import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Speak from "../components/speak";
import TradeIn from "../components/tradeIn";
import Close from "../components/close";
import Nav from "../components/nav";


const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Nav/>
            <main className={styles.main}>
                <Banner/>
                <TradeIn/>
                <Close/>
                <Speak/>
            </main>
            <footer>Copyright 2022</footer>
        </div>
    )
}

export default Home
